export const LoadingPageQuotes = () => {
  return [
    'The first Pokémon ever designed was Rhydon! The Rhydon statues found throughout the games are a little tribute to it',
    'Some think "Pokémon" is a Japanese word but it\'s actually a contraction of "Pocket Monsters," the original name of the franchise in Japan',
    'Satoshi Tajiri first developed the Pokémon concept back in 1989, having collected insects as a child',
    'The Pokémon Company generates an average of $15 billion each year',
    'Pokemon is a worldwide phenomenon that’s nearly 30 years old and Vietnam are the biggest fans',
    'In the original games, Arcanine was meant to be a legendary pokémon, along with Zapdos and Articuno',
    'Bulbasaur is the only unevolved dual type starter Pokémon',
    'Ivysaur is the only Generation I Pokémon whose name begins with the letter I',
    'Venusaur is a combination of the words Venus which refers to the Venus Flytrap plant, and the Greek word saur, meaning lizard',
    'Charmander is the tallest Fire-type starter Pokémon',
    'Charmeleon is capable of learning Leer in Generation I',
    'Charizard was voted as the favorite Pokémon by Official Nintendo Magazine readers in February 2012',
    'Squirtle is the first Water-type Pokémon in National Pokédex',
    'Wartortle gets its name from a combination of war/warrior, tortoise, and turtle',
    'Blastoise has the highest base Special Defense of all fully evolved starter Pokémon',
    'Caterpie was the first Pokémon to be seen evolving in the animé',
    'Metapod is known as a Cocoon Pokémon',
    'Butterfree has been trained by Trainers Ash, Drew, Ritchie and Solidad',
    'Weedle evolves at level 7, the lowest level required for any Pokémon to evolve by leveling up',
    'Kakuna has been shown evolving more than any other Pokémon in the animé',
    'Beedrill was originally going to be spelled with only one “L”',
    'Pidgey is the only Pokémon with a base stat total of 251',
    'Pidgeotto was caught by Ash in Ash Catches a Pokémon Since then, it was one of Ash’s main Pokémon',
    'Pidgeot is the only Pokémon with a base stat total of 469',
    'Rattata is the first pure Normal-type in National Pokédex order',
    'Raticate was classified as a Rat Pokémon in Pokémon Red and Blue, however, from Generation III onward, it is classified as a mouse',
    'Spearow is a combination of spear and sparrow or arrow',
    'Fearow weighs 38kg',
    'Ekans spells snake backwards, which is also Ekans’ species',
    'Arbok is the last Pokémon to be featured on the Kanto Pokérap',
    'Pikachu is voiced by Ikue Outani',
    'Raichu can be male or female, the difference in appearance is the female has smaller, blunted lightning bolt at the end of its tail',
    'Sandshrew is based on an animal called the pangolin, it’s a mammal that curls up into a ball, has sharp claws, and lives in desert regions',
    'Sandslash evolves from Sandshrew from level 22',
    'Nidoran♀ can lay eggs which have a chance of hatching into a Nidoran♂‚',
    'Nidorina are common in the Kanto region, but rare in Sinnoh',
    'Nidoqueen evolves from Nidorina when exposed to a Moon Stone',
    'Nidoran♂‚ made its first appearance in the animé in ‘Pokémon Fashion Flash‘',
    'Nidorino appeared in the very first episode, battling a Gengar in a battle Ash was watching on TV',
    'Nidoking, along with Nidoqueen are the only two Pokémon with a Poison/Ground type combination',
    'Clefairy was originally going to be the mascot of Pokémon instead of Pikachu',
    'Clefable is based on a fairy and pixie',
    'Vulpix was originally going to be called “Foxfire”',
    'Ninetales was misspelled as “Ninetails” in the Pokémon Trading Card Game for the Game Boy Color',
    'Jigglypuff is the only character to keep its original voice track through all three Super Smash Bros games',
    'Wigglytuff is 1m tall, which is 3’03”',
    'Zubat does not have eyes',
    'Golbat is the first Pokémon in the National Pokédex to gain a new evolution in a later generation',
    'Oddish has a scientific name, which is Oddium Wanderus It was first shown in the FireRed Pokédex entry',
    'Gloom is the only Pokémon to evolve into two different Pokémon with two different stones, other than Eevee',
    'Vileplume‘s species is Flower Pokémon',
    'Paras and its evolved form are the only Pokémon to have a 5x weakness due to the Ability Dry Skin',
    'Parasect has used Sleep Powder in the animé, however it cannot learn this in the games',
    'Venonat has red eyes and nose, however the shiny Venonat’s eyes and nose are blue',
    'Venomoth shares the same species name with Dustox They are both known as Poison Moth Pokémon',
    'Diglett has been shown to have no feet however it is mentioned as being one of the seven mysteries of Pokémon',
    'Dugtrio is the fastest Ground-type Pokémon',
    'Meowth is the first Pokémon in the animé to talk',
    'Persian‘s level-up moves are all Normal-type or Dark-type, except the move Power Gem',
    'Psyduck is the only Pokémon to learn Psychic by breeding',
    'Golduck is one of the few Pokémon that is obtainable in every game, including expansion games and remakes',
    'Mankey is the first Fighting-type Pokémon in National Pokédex order',
    'Primape‘s like to eat bananas',
    'Growlithe is a Puppy Pokémon, the only other Pokémon that has this species name is Lillipup',
    'Arcanine is said to be capable of running over 6,200 miles in a single day and night',
    'Poliwag has the same cry as Ditto in the games',
    'Poliwhirl is the first Pokémon in National Pokédex order to evolve by trading while holding an item',
    'Poliwrath is a combination the word polliwog, which is a tadpole, and wrath, meaning anger',
    'Abra has the highest Special Attack of all unevolved Pokémon',
    'Kadabra is based on a magician and also a spoon-bender',
    'Alakazam‘s have a shorter moustache if they are female',
    'Machop can learn Strength, which is the only HM move it can learn',
    'Machoke weighs 705 kg',
    'Machamp is one of the four Pokémon having a total of four arms',
    'Bellsprout eat insects and takes in nutrients from the soil',
    'Weepinbell first appeared in the animé in The School of Hard Knocks',
    'Victreebel and its pre-evolutions are based on carnivorous pitcher plants',
    'Tentacool is weak against Ground, Electric and Psychic type moves',
    'Tentacruel is said to have eighty tentacles, however only about ten are often seen',
    'Geodude are often shown to be floating, however it cannot have the Levitate Ability, and it can’t learn Magnet Rise',
    'Graveler‘s diet mainly consists of moss-covered rocks',
    'Golem are able to withdraw their head, arms, and legs into their shell and roll at high speeds',
    'Ponyta in shiny form has blue flames',
    'Rapidash has no flames for a split second, in the first movie',
    'Slowpoke was originally going to be called “Slowmo”',
    'Slowbro and Slowking are the only Pokémon that can de-evolve in the anime',
    'Magnemite is the first Steel-type Pokémon in National Pokédex order',
    'Magneton has been used by more rival characters than any other Pokémon',
    'Farfetch’d is the only non-glitch Pokémon with an apostrophe in its name',
    'Doduo have brown necks if they are female and males have black necks',
    'Dodrio is based on the dodo, a flightless bird, however it is able to learn Fly',
    'Seel is the only non-Ice-type Pokémon to have the Ice Body Ability',
    'Dewgong is the first Ice Pokémon in National Pokédex order',
    'Grimer is one of two Pokémon who don’t change weight during evolution, the other is Gastly',
    'Muk is tied with Mew for the shortest English name out of all Pokémon',
    'Shellder learns Hydro Pump at level 61',
    'Cloyster is the only Ice-type Pokémon in the purple color group',
    'Gastly and its evolution Haunter are the lightest Pokémon in existence',
    'Haunter has a slightly different cry starting in Generation III',
    'Gengar is theorised to be a shadow of a Clefable',
    'Onix is the longest Pokémon that can hatch from an Egg',
    'Drowzee is based on the Japanese myth of the baku, creatures who eat bad dreams of sleeping people',
    'Hypno in shiny form is purple/pink in color',
    'Krabby can grow back its pincers in a short amount of time if they are lost during battle',
    'Kingler mainly eat Shellder for their diet',
    'Voltorb has the lowest Attack stat of all Electric-type Pokémon',
    'Electrode is based on a living Poké Ball, and is often mistaken for one',
    'Exeggcute can be found in the Dream World in Pleasant Forest',
    'Exeggutor and its pre-evolved form are the only known Pokémon that learn Barrage',
    'Cubone is only 40cm in height and weighs 65kg',
    'Marowak sometimes is found holding a Thick Club, however it’s only a 5% chance since Generation III',
    'Hitmonlee is a combination of hit, monster and Lee, which references Bruce Lee',
    'Hitmonchan is based on Jackie Chan',
    'Lickitung‘s name was misspelled “Likitung” in the Kanto Pokérap',
    'Koffing was originally known as “Ny”, representing New York City’s polluted air',
    'Weezing has the highest Defense out of all Poison-type Pokémon',
    'Rhyhorn has the exact same cry as Charizard in the games',
    'Rhydon was the first Pokémon ever created!',
    'Chansey is a female-only species with no male counterpart',
    'Tangela is the first pure Grass-type Pokémon in National Pokédex order, also the only pure Grass-type in Generation I',
    'Kangaskhan are born with a baby already in their pouch, the baby Kangaskhan is not a separate Pokémon',
    'Horsea cannot learn any physical attacks without TMs',
    'Seadra‘s are capable of swimming backwards while facing forward',
    'Goldeen was one of three original Pokémon Misty acquired',
    'Seaking and its pre-evolved form are the only Pokémon that can learn Waterfall through leveling up',
    'Staryu‘s Japanese name is Hitodeman, which roughly translates to “starfish man”',
    'Starmie is a genderless species',
    'Mr Mime are not all male, it is just as common to see a female',
    'Scyther hates the color red, according to the animé episode Showdown in Dark City',
    'Jynx is a female-only species, based on a fat, bulky human woman',
    'Electabuzz evolves into Electivire when traded holding an Electirizer',
    'Magmar first appeared under the ownership of Blaine',
    'Pinsir is currently the only non-Fighting-type Pokémon to learn Vital Throw',
    'Tauros is based on the Zodiac Taurus, the bull',
    'Magikarp living for many years can leap a mountain using Splash',
    'Gyarados has the greatest increase of its base stat total of any Pokémon compared to its pre-evolution',
    'Lapras has the highest base HP of all Ice-types',
    'Ditto has the same cry as Poliwag',
    'Eevee‘s evolutionary family has the most evolutionary relatives out of any other Pokémon',
    'Vaporeon is the only Eeveelution that does not share any weakness with another',
    'Jolteon is the lightest Eeveelution',
    'Flareon is the only fully-evolved Fire-type Pokémon that cannot learn SolarBeam',
    'Porygon is the only Pokémon that evolves by trade twice',
    'Omanyte‘s are resurrected from a Helix Fossils',
    'Omastar first appeared in episode 46, Attack of the Prehistoric Pokémon',
    'Kabuto and its evolved form are the only non-Steel-type Pokémon able to learn Metal Sound via leveling up',
    'Kabutops‘ scientific name is Kabutops maximis, it is one of two Pokémon to have a scientific name, the other being Oddish',
    'Aerodactyl is the fastest Rock-type Pokémon, with a base Speed of 130',
    'Snorlax is the heaviest Pokémon that has a gender and the heaviest Normal-type Pokémon',
    'Articuno is the only Pokemon that did not appear in Season 1',
    'Zapdos and Jolteon have very similar names in Japanese: Zapdos is サンダー (Thunder), while Jolteon is サンダース (Thunders)',
    'Moltres is the only Fire-type Pokémon to learn SolarBeam by level-up',
    'Dratini is the lightest Dragon-type Pokémon',
    'Dragonair was originally named “Dragyn”',
    'Dragonite are very rare in the wild',
    'Mewtwo is a clone of the Pokémon Mew, yet it comes before Mew in the Pokédex',
    'Mew was a little-known secret when Pokémon Red and Green were first released in Japan Even Nintendo was not initially aware that Mew was programed it into the game',
  ];
};
